import { fetchUsername } from '@/action/auth';
import type { Metadata } from 'next';

import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get('accessToken')?.value;

  if (!accessToken) {
    redirect('/');
  }

  const username = await fetchUsername();
  console.log('username!', username);
  if (!username) {
    redirect('/');
  }

  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-gray-900 to-black text-white">
      {/* Header */}
      <Header username={username} />

      {/* Main Content */}
      <main className="flex-grow">
        <div className="container max-w-7xl mx-auto p-6">{children}</div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-4">
        <div className="container mx-auto text-center">
          <p className="text-gray-400">
            &copy; 2024 Stock Signal. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
