import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-full min-h-screen">
      {/* 헤더 */}
      <header className="bg-blue-500 text-white py-4 shadow-md">
        <div className="container mx-auto flex items-center justify-between px-6">
          <div className="flex items-center space-x-2">
            <h1 className="text-2xl font-bold">Stock Signal</h1>
          </div>
          <nav>
            <ul className="flex items-center space-x-4">
              <li>
                <Link href="/" className="text-white hover:text-gray-200">
                  홈
                </Link>
              </li>
              <li>
                <Link href="/stocks" className="text-white hover:text-gray-200">
                  한국 주식
                </Link>
              </li>
              {/* <li>
                <a href="/stocks/us" className="text-white hover:text-gray-200">
                  미국 주식
                </a>
              </li> */}
            </ul>
          </nav>
        </div>
      </header>

      {/* 메인 콘텐츠 */}
      <main className="flex-grow container mx-auto p-6">{children}</main>

      {/* 푸터 */}
      <footer className="bg-gray-800 text-white py-4">
        <div className="container mx-auto text-center">
          <p>&copy; 2024 Stock Signal. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
